package web

import (
	"errors"
	"fmt"
	"io/fs"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/gin-gonic/gin"
	"github.com/marein/dev-cockpit/internal/coder"
	"github.com/marein/dev-cockpit/internal/coder/claude"
	codercopilot "github.com/marein/dev-cockpit/internal/coder/copilot"
	"github.com/marein/dev-cockpit/internal/config"
	"github.com/marein/dev-cockpit/internal/project"
	"github.com/marein/dev-cockpit/internal/recent"
	"github.com/marein/dev-cockpit/internal/tmux"
	"github.com/marein/dev-cockpit/internal/web/render"
)

// A session as claude records it, shortened and anonymised, with the
// things the record keeps that nobody said: the reminder behind the words,
// the caveat and the output of a local command, the slash command, the
// tool results, the thinking, the interrupt marker. The caveat carries
// isMeta as claude writes it, so it falls out before any stripping; the strip
// of a caveat without that mark is pinned by
// TestAUserMessageIsOnlyWhatThePersonTyped in the claude package.
var copyFixture = []string{
	`{"parentUuid":null,"isSidechain":false,"promptId":"p1","type":"user","message":{"role":"user","content":[{"type":"text","text":"list the files\n\n<system-reminder>\nThe file a.go was modified by the user.\n</system-reminder>"}]},"uuid":"u-ask","timestamp":"2026-09-18T10:50:56.891Z","cwd":"/home/me/proj","sessionId":"s1","version":"2.1.280"}`,
	`{"parentUuid":"u-ask","isSidechain":false,"message":{"model":"claude-fable-5-1","id":"msg_01","type":"message","role":"assistant","content":[{"type":"thinking","thinking":"I will list them.","signature":"CAQ"},{"type":"tool_use","id":"toolu_01","name":"Bash","input":{"command":"ls /tmp\necho done","description":"List files"}}]},"type":"assistant","uuid":"a-bash","timestamp":"2026-09-18T10:50:59.382Z","cwd":"/home/me/proj","sessionId":"s1","version":"2.1.280"}`,
	`{"parentUuid":"a-bash","isSidechain":false,"type":"user","message":{"role":"user","content":[{"tool_use_id":"toolu_01","type":"tool_result","content":"caps\nhooks\nSECRETRESULT","is_error":false}]},"uuid":"u-bashdone","timestamp":"2026-09-18T10:51:13.915Z","toolUseResult":{"stdout":"caps\nhooks"},"cwd":"/home/me/proj","sessionId":"s1","version":"2.1.280"}`,
	`{"parentUuid":"u-bashdone","isSidechain":false,"message":{"model":"claude-fable-5-1","id":"msg_02","type":"message","role":"assistant","content":[{"type":"tool_use","id":"toolu_02","name":"WebFetch","input":{"url":"https://example.org/x","prompt":"read it"}}]},"type":"assistant","uuid":"a-fetch","timestamp":"2026-09-18T10:51:14.000Z","cwd":"/home/me/proj","sessionId":"s1","version":"2.1.280"}`,
	`{"parentUuid":"a-fetch","isSidechain":false,"type":"user","message":{"role":"user","content":[{"type":"tool_result","content":"Claude Code is unable to fetch from example.org\nmore detail","is_error":true,"tool_use_id":"toolu_02"}]},"uuid":"u-fetchfail","timestamp":"2026-09-18T10:51:15.000Z","cwd":"/home/me/proj","sessionId":"s1","version":"2.1.280"}`,
	`{"parentUuid":"u-fetchfail","isSidechain":false,"message":{"model":"claude-fable-5-1","id":"msg_03","type":"message","role":"assistant","content":[{"type":"text","text":"Two files:\n\n- caps\n- hooks"}]},"type":"assistant","uuid":"a-reply","timestamp":"2026-09-18T10:51:16.363Z","cwd":"/home/me/proj","sessionId":"s1","version":"2.1.280"}`,
	`{"parentUuid":"a-reply","isSidechain":false,"type":"user","message":{"role":"user","content":[{"type":"text","text":"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>"}]},"isMeta":true,"uuid":"u-caveat","timestamp":"2026-09-18T11:01:00.000Z","cwd":"/home/me/proj","sessionId":"s1","version":"2.1.280"}`,
	`{"parentUuid":"u-caveat","isSidechain":false,"type":"user","message":{"role":"user","content":[{"type":"text","text":"<command-name>/compact</command-name>\n            <command-message>compact</command-message>\n            <command-args>keep the list</command-args>"}]},"uuid":"u-command","timestamp":"2026-09-18T11:01:00.100Z","cwd":"/home/me/proj","sessionId":"s1","version":"2.1.280"}`,
	`{"parentUuid":"u-command","isSidechain":false,"type":"user","message":{"role":"user","content":[{"type":"text","text":"<local-command-stdout>Compacted </local-command-stdout>"}]},"uuid":"u-stdout","timestamp":"2026-09-18T11:01:01.000Z","cwd":"/home/me/proj","sessionId":"s1","version":"2.1.280"}`,
	`{"parentUuid":"u-stdout","isSidechain":false,"promptId":"p2","type":"user","message":{"role":"user","content":[{"type":"text","text":"pick a color"}]},"uuid":"u-color","timestamp":"2026-09-18T10:51:23.882Z","cwd":"/home/me/proj","sessionId":"s1","version":"2.1.280"}`,
	`{"parentUuid":"u-color","isSidechain":false,"message":{"model":"claude-fable-5-1","id":"msg_04","type":"message","role":"assistant","content":[{"type":"tool_use","id":"toolu_03","name":"AskUserQuestion","input":{"questions":[{"question":"Which color do you like?","header":"Color","multiSelect":false,"options":[{"label":"Red","description":"a warm one"},{"label":"Blue","description":"a cool one"}]}]}}]},"type":"assistant","uuid":"a-askuse","timestamp":"2026-09-18T10:51:26.210Z","cwd":"/home/me/proj","sessionId":"s1","version":"2.1.280"}`,
	`{"parentUuid":"a-askuse","isSidechain":false,"type":"user","message":{"role":"user","content":[{"type":"text","text":"[Request interrupted by user for tool use]"}]},"uuid":"u-abort","timestamp":"2026-09-18T10:57:47.735Z","cwd":"/home/me/proj","sessionId":"s1","version":"2.1.280"}`,
}

// copyFixtureConversation parses the fixture through the real claude
// reader, the path every page of the copy view takes.
func copyFixtureConversation(t *testing.T) []coder.Message {
	t.Helper()
	home := t.TempDir()
	t.Setenv("HOME", home)
	dir := filepath.Join(home, ".claude", "projects", "-home-me-proj")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "s1.jsonl"), []byte(strings.Join(copyFixture, "\n")+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	all, err := claude.New("", nil).SessionConversation("s1")
	if err != nil {
		t.Fatalf("read the fixture: %v", err)
	}
	return all
}

func renderCopyPage(t *testing.T, data render.CoderCopyData) string {
	t.Helper()
	tmpl := render.HTMLTemplate(func(p string) string { return p }, "test", "test", nil)
	var out strings.Builder
	if err := tmpl.ExecuteTemplate(&out, "coder_copy_page.gohtml", data); err != nil {
		t.Fatalf("render page: %v", err)
	}
	return out.String()
}

// What the record keeps around the conversation never reaches a bubble: no
// tag of the CLI's, no tool result, no thinking, no system text. The
// rendered markup is searched for the words themselves.
func TestTheBubblesCarryNoRecordMarkup(t *testing.T) {
	all := copyFixtureConversation(t)
	html := renderCopyPage(t, render.CoderCopyData{Messages: copyViews("Claude", all)})
	for _, forbidden := range []string{"system-reminder", "command-name", "command-message", "command-args", "tool_result", "Caveat", "local-command", "SECRETRESULT", "I will list them", "modified by the user", "more detail", "unable to fetch", "interrupted", "Blue"} {
		if strings.Contains(html, forbidden) {
			t.Fatalf("%q stands in the rendered page:\n%s", forbidden, html)
		}
	}
	for _, wanted := range []string{
		`data-copy-command>/compact keep the list<`,
		`data-copy-tool="Bash"`,
		`ls /tmp`,
		`data-copy-tool="AskUserQuestion"`,
		`Which color do you like?`,
		`<li>caps</li>`,
		`<template data-copy-source>Two files:`,
	} {
		if !strings.Contains(html, wanted) {
			t.Fatalf("%q is missing from the rendered page:\n%s", wanted, html)
		}
	}
	if strings.Count(html, `data-role="user"`) != 3 {
		t.Fatalf("want three user bubbles (the words, the command, the second words):\n%s", html)
	}
	if strings.Count(html, `data-copy-message`) != 4 {
		t.Fatalf("want a copy button on every message with words, none on a turn of tool calls alone:\n%s", html)
	}
}

// A page with older messages above it offers them by the id of its first
// message, and an empty page says why.
func TestAPageOffersWhatStandsAboveIt(t *testing.T) {
	all := copyFixtureConversation(t)
	html := renderCopyPage(t, render.CoderCopyData{Messages: copyViews("Claude", all[2:]), Dropped: 2, Before: all[2].ID})
	if !strings.Contains(html, `data-copy-more="`+all[2].ID+`"`) {
		t.Fatalf("no way to the older messages:\n%s", html)
	}
	if empty := renderCopyPage(t, render.CoderCopyData{Note: "Nothing was said yet."}); !strings.Contains(empty, "Nothing was said yet.") || strings.Contains(empty, "data-copy-more") {
		t.Fatalf("empty page:\n%s", empty)
	}
}

// conversationCoder is a coder whose record answers the given messages or
// the given error.
type conversationCoder struct {
	coder.Coder
	all []coder.Message
	err error
}

func (c conversationCoder) ID() string { return "claude" }

func (c conversationCoder) SessionConversation(string) ([]coder.Message, error) {
	return c.all, c.err
}

const conversationSession = "11111111-1111-4111-8111-111111111111"

// serveConversation answers the conversation page of a running session over
// the given record.
func serveConversation(t *testing.T, record conversationCoder, query string) string {
	t.Helper()
	gin.SetMode(gin.TestMode)
	rec := httptest.NewRecorder()
	c, engine := gin.CreateTestContext(rec)
	engine.SetHTMLTemplate(render.HTMLTemplate(func(p string) string { return p }, "test", "test", nil))
	c.Request = httptest.NewRequest(http.MethodGet, "/coders/"+conversationSession+"/conversation"+query, nil)
	renderCoderConversation(c, coder.NewManager(config.Config{}, nil, record, nil), conversationSession)
	if rec.Code != http.StatusOK {
		t.Fatalf("status %d: %s", rec.Code, rec.Body.String())
	}
	return rec.Body.String()
}

func words(id, role, text string) coder.Message {
	return coder.Message{ID: id, Role: role, Parts: []coder.Part{{Kind: coder.PartText, Text: text}}}
}

// A terminal that is not running has no conversation to show.
func TestTheConversationOfATerminalThatIsNotRunningIsNotFound(t *testing.T) {
	gin.SetMode(gin.TestMode)
	projects := project.NewRepository(t.TempDir(), recent.New(filepath.Join(t.TempDir(), "recent.json")))
	s := &Server{
		coders:   []*coder.Manager{coder.NewManager(config.Config{}, tmux.New(), codercopilot.New(nil), projects)},
		projects: projects,
	}
	const id = "ffffffff-ffff-4fff-8fff-ffffffffffff"
	rec := httptest.NewRecorder()
	c, _ := gin.CreateTestContext(rec)
	c.Request = httptest.NewRequest(http.MethodGet, "/coders/"+id+"/conversation", nil)
	c.Params = gin.Params{{Key: "id", Value: id}}
	s.handleCoderConversation(c)
	if rec.Code != http.StatusNotFound {
		t.Fatalf("want a terminal that is not running not found, got %d: %s", rec.Code, rec.Body.String())
	}
}

// A record that is not written yet is a conversation nobody spoke in, a
// record that could not be read says so and never reads as empty.
func TestAConversationThatCouldNotBeReadIsNoEmptyOne(t *testing.T) {
	missing := serveConversation(t, conversationCoder{err: fmt.Errorf("open: %w", fs.ErrNotExist)}, "")
	if !strings.Contains(missing, "Nothing was said yet.") {
		t.Fatalf("a record not written yet:\n%s", missing)
	}
	if yet := serveConversation(t, conversationCoder{err: coder.NoRecordYet("This session has no record to read.")}, ""); !strings.Contains(yet, "Nothing was said yet.") {
		t.Fatalf("NoRecordYet:\n%s", yet)
	}
	broken := serveConversation(t, conversationCoder{err: errors.New("This session's record could not be read.")}, "")
	if strings.Contains(broken, "Nothing was said yet.") || !strings.Contains(broken, "This session&#39;s record could not be read.") {
		t.Fatalf("a record that could not be read:\n%s", broken)
	}
	denied := serveConversation(t, conversationCoder{err: &fs.PathError{Op: "open", Path: "/x", Err: fs.ErrPermission}}, "")
	if strings.Contains(denied, "Nothing was said yet.") || !strings.Contains(denied, "Permission denied.") {
		t.Fatalf("a record nobody may read:\n%s", denied)
	}
}

// before reaches the reading: the page stands above the message it names.
func TestThePageBeforeAMessageIsServed(t *testing.T) {
	record := conversationCoder{all: []coder.Message{
		words("m1", coder.RoleUser, "first words"),
		words("m2", coder.RoleCoder, "first answer"),
		words("m3", coder.RoleUser, "second words"),
	}}
	older := serveConversation(t, record, "?before=m3")
	if !strings.Contains(older, `data-message-id="m2"`) || strings.Contains(older, `data-message-id="m3"`) {
		t.Fatalf("the page before m3:\n%s", older)
	}
	if changed := serveConversation(t, record, "?before=gone"); !strings.Contains(changed, coder.ErrConversationChanged.Error()) {
		t.Fatalf("a before the record no longer holds:\n%s", changed)
	}
}
